apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    # Add your nginx.conf content here
    events {}

    http {

        include       mime.types;
        default_type  application/octet-stream;

        # Log format
        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        # Access and error logs
        access_log  /var/log/nginx/access.log  main;
        error_log   /var/log/nginx/error.log;


        # Redirect HTTP to HTTPS
        server {
            listen 80;
            server_name localhost;

            location / {
                return 301 https://$host$request_uri;
            }
        }

        # HTTPS server
        server {
            listen 443 ssl;
            server_name localhost;

            ssl_certificate /etc/nginx/ssl/certificate.pem;
            ssl_certificate_key /etc/nginx/ssl/private_key.pem;
            ssl_password_file /etc/nginx/ssl/cert_password;

            ssl_protocols TLSv1.2 TLSv1.3;
            ssl_ciphers HIGH:!aNULL:!MD5;

            location / {
                proxy_pass http://grafana-monitoring:3000;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;

                # Optional: Adjust timeouts
                proxy_connect_timeout       1800;
                proxy_send_timeout          1800;
                proxy_read_timeout          1800;
                send_timeout                1800;
            }
        }
    }
