{
 "title": "SSIS & Python Programs Monitoring",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "SSIS Package Failures Last 2 days",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "ADHOC_LightSone",
     "rawSql": "  SELECT\r\n  TOP(50) package_name,\r\n  COUNT(status)\r\nFROM\r\n  SSISDB.catalog.executions\r\nWHERE created_time BETWEEN  DATEADD(DAY, -2, GETDATE()) AND GETDATE()\r\nAND [status] IN (4, 6)\r\nGROUP BY\r\n  package_name"
    }
   ]
  },
  {
   "title": "SSIS Packages Currently Running",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "ADHOC_LightSone",
     "rawSql": "DECLARE @RunningStatus INT = 2;\r\n\r\nWITH CTE_Packages\r\nAS (\r\nSELECT DATEDIFF(MINUTE, CAST(start_time AS DATETIME), CAST(end_time AS DATETIME)) AS Duration, * FROM [SSISDB].[catalog].[executions]\r\nWHERE package_name IN ( SELECT package_name FROM [SSISDB].[catalog].[executions] WHERE status = @RunningStatus)\r\n\r\n)\r\n\r\nSELECT a.package_name AS PackageName, CAST(AVG(Duration) AS VARCHAR(10)) + ' Mins'  AS AVG_Duration\r\n, CASE \r\n\tWHEN b.RunningDuration > 120\r\n\t\tTHEN CAST(CAST(b.RunningDuration AS INT)/60 AS VARCHAR(10)) + ' Mins'\r\n\tELSE CAST(b.RunningDuration AS VARCHAR(10)) + ' s'\r\n\tEND\t\t\t\t\t\t\t\t\t\t\t\t\tAS CurrentDuration\r\nFROM CTE_Packages AS a\r\nJOIN ( SELECT DATEDIFF(SECOND, CAST(start_time AS DATETIME), GETDATE()) AS RunningDuration, package_name FROM [SSISDB].[catalog].[executions] WHERE status = @RunningStatus) AS b\r\n    ON a.package_name = b.package_name\r\nGROUP BY a.package_name, b.RunningDuration"
    }
   ]
  },
  {
   "title": "Speed Successful Executions (Last Week)",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "dataset": "ADHOC_LightSone",
     "rawSql": "SELECT [PackageName]\r\n      ,[DateTimeStart] AS DateExecuted\r\n  FROM [MKS_MasterData].[dbo].[DimAudit]\r\n  WHERE CompletedAllSteps = 1\r\n  AND DateTimeStart > DATEADD(WEEK, -1, GETDATE())\r\n  AND SuccessFlag = 'Y'\r\n  ORDER BY DateExecuted DESC"
    }
   ]
  },
  {
   "title": "Scheduled SQL Agent Jobs Errors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "dataset": "ADHOC_LightSone",
     "rawSql": "DECLARE @DaysWindow INT = 30;\r\n\r\nWITH CTE_Date\r\nAS \r\n(SELECT DateKey\r\n\t  , Date \r\n FROM [MKS_MasterData].[dbo].[DimDate] \r\n WHERE Date BETWEEN DATEADD(DAY, -@DaysWindow, GETDATE()) AND GETDATE()\r\n)\r\n\r\n, CTE_Errors\r\nAS\r\n(\r\n  SELECT\r\n    jh.run_date\r\n  , COUNT(*) AS ErrorCount\r\n  FROM ( SELECT DISTINCT job_id FROM [msdb].[dbo].[sysjobschedules]) js\r\n  \r\n  LEFT JOIN [msdb].[dbo].[sysjobs] j\r\n    ON j.[job_id] = js.[job_id]\r\n \r\n  LEFT JOIN [msdb].[dbo].[sysjobhistory] jh\r\n    ON jh.[job_id] = js.[job_id]\r\n\r\n WHERE [message] LIKE '%job fail%'\r\n  AND CAST(SUBSTRING(CAST(run_date AS VARCHAR(8)), 1,4) + '-' + SUBSTRING(CAST(run_date AS VARCHAR(8)), 5,2) + '-' + SUBSTRING(CAST(run_date AS VARCHAR(8)), 7,2) AS DATETIME) \r\n        BETWEEN DATEADD(DAY, -@DaysWindow, GETDATE()) AND  GETDATE()\r\n GROUP BY run_date\r\n)\r\n\r\n\r\nSELECT d.Date\r\n, ISNULL(ErrorCount, 0) AS ErrorCount\r\nFROM CTE_Date d\r\n\r\nLEFT JOIN CTE_Errors e\r\n\tON d.DateKey = e.run_date\r\n"
    }
   ]
  },
  {
   "title": "Python Applications Error Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "dataset": "ADHOC_LightSone",
     "rawSql": "DECLARE @DaysWindow INT = 30;\r\n\r\nWITH CTE_Date\r\nAS \r\n(SELECT DateKey\r\n\t  , Date \r\n FROM [MKS_MasterData].[dbo].[DimDate] \r\n WHERE Date BETWEEN DATEADD(DAY, -@DaysWindow, GETDATE()) AND GETDATE()\r\n)\r\n\r\n, CTE_Errors\r\nAS\r\n(\r\n  SELECT [AppName]\r\n      ,COUNT(*) AS ErrorCount\r\n      ,CAST([Timestamp] AS DATE) AS [Date]\r\n  FROM [MKS_MasterData].[dbo].[PythonLogs]\r\n  WHERE LogMessage LIKE '%ERROR%'\r\n  AND [Timestamp] BETWEEN DATEADD(MONTH, -@DaysWindow, GETDATE()) AND GETDATE()\r\n  GROUP BY [AppName], CAST([Timestamp] AS DATE)\r\n)\r\n\r\n\r\nSELECT d.Date\r\n, ISNULL(ErrorCount, 0) AS ErrorCount\r\nFROM CTE_Date d\r\n\r\nLEFT JOIN CTE_Errors e\r\n\tON d.Date = e.[Date]\r\n\r\n\r\n"
    }
   ]
  },
  {
   "title": "SQL Agent Executions Today",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "dataset": "ADHOC_LightSone",
     "rawSql": "SELECT j.[name]\r\n, COUNT(*) AS Executions\r\nFROM (SELECT * FROM [msdb].[dbo].[sysjobhistory] WHERE step_id <> 0 ) AS jh\r\n\r\nJOIN [msdb].[dbo].[sysjobs] j\r\n  ON j.[job_id] = jh.[job_id]\r\n\r\nWHERE CAST(SUBSTRING(CAST(run_date AS VARCHAR(8)), 1,4) + '-' + SUBSTRING(CAST(run_date AS VARCHAR(8)), 5,2) + '-' + SUBSTRING(CAST(run_date AS VARCHAR(8)), 7,2) AS DATETIME)  = CAST(GETDATE() AS DATE)\r\n        -- BETWEEN DATEADD(DAY, -2, GETDATE()) AND  GETDATE()\r\n\r\nGROUP BY j.[name]\r\n"
    }
   ]
  },
  {
   "title": "SSIS Error Logs (Last 2 Days)",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "dataset": "ADHOC_LightSone",
     "rawSql": "SELECT ce.project_name AS SSISDB_Project\r\n, ce.package_name      AS PackageName\r\n, pe.message           AS ErrorMessage\r\n, message_time         AS EventDateTime\r\nFROM \r\n    SSISDB.catalog.executions ce\r\nJOIN  SSISDB.catalog.event_messages pe\r\n    ON pe.operation_id = ce.execution_id\r\nWHERE event_name = 'OnError'\r\nAND message_time BETWEEN DATEADD(DAY, -2, GETDATE()) AND GETDATE()\r\nORDER by message_time DESC"
    }
   ]
  },
  {
   "title": "Python Applications Error Logs (Past 2 Days)",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "dataset": "ADHOC_LightSone",
     "rawSql": "SELECT [AppName]\r\n    ,[LogMessage]\r\n  FROM [MKS_MasterData].[dbo].[PythonLogs]\r\n  WHERE [Timestamp] BETWEEN DATEADD(DAY, -2, GETDATE()) AND GETDATE()\r\n  AND LogMessage LIKE '%ERROR%'\r\n  ORDER BY Timestamp DESC"
    }
   ]
  }
 ]
}