apiVersion: v1
kind: Service
metadata:
  name: principa-monitoring
  namespace: default
spec:
  selector:
    app: principa-monitoring
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 80
